'use server';

import { z } from 'zod';
import { collection, addDoc, serverTimestamp, getFirestore } from 'firebase/firestore';
import { initializeApp, getApps } from 'firebase/app';

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

const app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApps()[0];
const db = getFirestore(app);

const formSchema = z.object({
  name: z.string().min(2, 'Name must be at least 2 characters.'),
  companyName: z.string().optional(),
  phone: z.string().min(10, 'Please enter a valid 10-digit phone number.'),
  email: z.string().email('Please enter a valid email address.'),
  street: z.string().min(3, 'Street address is required.'),
  city: z.string().min(2, 'City is required.'),
  state: z.string().min(2, 'State is required.'),
  zip: z.string().min(5, 'ZIP code is required.'),
  purpose: z.string().optional(),
});

const STORE_ID = 'store_main'; // Assuming a single store for this public form

// This action now uses the client SDK and should be called from the client
export async function addPendingCustomer(data: z.infer<typeof formSchema>): Promise<{ success: boolean; error?: string; }> {
    try {
        const validatedData = formSchema.parse(data);

        const customersCollection = collection(db, 'stores', STORE_ID, 'customers');
        
        // The document ID will be auto-generated by Firestore upon addDoc
        const newCustomerData = {
            storeId: STORE_ID,
            name: validatedData.name,
            companyName: validatedData.companyName || '',
            phone: validatedData.phone,
            email: validatedData.email,
            isApproved: false, // Default to not approved
            createdAt: serverTimestamp(),
            purpose: validatedData.purpose || '',
            addresses: [{
                street: validatedData.street,
                city: validatedData.city,
                state: validatedData.state,
                zip: validatedData.zip,
                country: 'India',
                isPrimary: true,
            }],
            title: '',
            gstNumber: '',
        };
        
        // Using addDoc will create a new document with an auto-generated ID
        const docRef = await addDoc(customersCollection, newCustomerData);

        // Here we could update the doc with its own ID if needed, but it's often not necessary
        // await updateDoc(docRef, { id: docRef.id });

        return { success: true };
    } catch (error: any) {
        console.error('Error adding pending customer:', error);

        if (error instanceof z.ZodError) {
            return { success: false, error: "Validation failed. Please check your input." };
        }
        
        return { success: false, error: error.message || 'An internal error occurred. The issue has been logged.' };
    }
}
